export const moviesData = {
    "Joy": {
        "quote": "Ah, the joyous light within you dances like a sunbeam\u2014radiant and uplifting! Dive into these cinematic treasures that celebrate life\u2019s vivid hues, each story waiting to embrace your spirit and spark even more joy. Let the magic unfold!",
        "color": "joy",
        "themeColor": "#facc15",
        "movies": [
            {
                "id": 1,
                "title": "La La Land",
                "genre": "Musical / Romance",
                "year": 2016,
                "rating": "8.0",
                "duration": "128 min",
                "match": "98%",
                "desc": "A jazz pianist falls for an aspiring actress in Los Angeles.",
                "reason": "Pure cinematic joy with dazzling musical numbers.",
                "img": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0O5J.jpg"
            },
            {
                "id": 2,
                "title": "Am\u00e9lie",
                "genre": "Comedy / Romance",
                "year": 2001,
                "rating": "8.3",
                "duration": "122 min",
                "match": "95%",
                "desc": "Am\u00e9lie is an innocent girl in Paris with her own sense of justice.",
                "reason": "A whimsical tale of finding joy in little things.",
                "img": "https://image.tmdb.org/t/p/w500/mWhws1ZkXkEbsD2rD1I1OimS7uV.jpg"
            },
            {
                "id": 3,
                "title": "Paddington 2",
                "genre": "Adventure / Comedy",
                "year": 2017,
                "rating": "7.8",
                "duration": "103 min",
                "match": "94%",
                "desc": "Paddington takes up a job to buy a pop-up book.",
                "reason": "Radiating pure kindness and infectious happiness.",
                "img": "https://image.tmdb.org/t/p/w500/kKROA5YpS2k05AOWU9sM55ZhefE.jpg"
            },
            {
                "id": 4,
                "title": "Spider-Man: Into the Spider-Verse",
                "genre": "Animation / Action",
                "year": 2018,
                "rating": "8.4",
                "duration": "117 min",
                "match": "92%",
                "desc": "Teen Miles Morales becomes the Spider-Man of his universe.",
                "reason": "A visually stunning and deeply joyful superhero journey.",
                "img": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg"
            },
            {
                "id": 5,
                "title": "Singin' in the Rain",
                "genre": "Musical / Comedy",
                "year": 1952,
                "rating": "8.3",
                "duration": "103 min",
                "match": "91%",
                "desc": "A silent film star falls for a chorus girl.",
                "reason": "The absolute pinnacle of feel-good cinema.",
                "img": "https://image.tmdb.org/t/p/w500/8g0q2wAOPQ6kQ1h7bQ7D4aHlT.jpg"
            },
            {
                "id": 6,
                "title": "My Neighbor Totoro",
                "genre": "Animation / Family",
                "year": 1988,
                "rating": "8.1",
                "duration": "86 min",
                "match": "90%",
                "desc": "Two girls interact with friendly wood spirits.",
                "reason": "Pure, unadulterated childhood wonder and joy.",
                "img": "https://image.tmdb.org/t/p/w500/rtGDOeG9LzoerkLSKv5iK2ndgE.jpg"
            },
            {
                "id": 7,
                "title": "Little Miss Sunshine",
                "genre": "Comedy / Drama",
                "year": 2006,
                "rating": "7.8",
                "duration": "101 min",
                "match": "89%",
                "desc": "A family road trip to a beauty pageant.",
                "reason": "Heartwarming and hilarious in equal measure.",
                "img": "https://image.tmdb.org/t/p/w500/fRtuR2wKpwv55T7zIfbI7l4l2bZ.jpg"
            },
            {
                "id": 8,
                "title": "The Princess Bride",
                "genre": "Adventure / Family",
                "year": 1987,
                "rating": "8.0",
                "duration": "98 min",
                "match": "88%",
                "desc": "A farmhand must rescue his true love.",
                "reason": "A delightful, endlessly quotable fairy tale.",
                "img": "https://image.tmdb.org/t/p/w500/dzjnZk2a0W0iRzJOhP0E7Y2rV0a.jpg"
            },
            {
                "id": 9,
                "title": "Ratatouille",
                "genre": "Animation / Comedy",
                "year": 2007,
                "rating": "8.1",
                "duration": "111 min",
                "match": "87%",
                "desc": "A rat who can cook makes an unusual alliance with a kitchen worker.",
                "reason": "A delicious celebration of passion and art.",
                "img": "https://image.tmdb.org/t/p/w500/npLVcsNJllD1sA0u6J8nEaZpALq.jpg"
            },
            {
                "id": 10,
                "title": "Forrest Gump",
                "genre": "Drama / Romance",
                "year": 1994,
                "rating": "8.8",
                "duration": "142 min",
                "match": "86%",
                "desc": "The presidencies of Kennedy and Johnson, the Vietnam War, and more from the perspective of an Alabama man.",
                "reason": "An uplifting testament to a life fully lived.",
                "img": "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg"
            }
        ]
    },
    "Anger": {
        "quote": "I hear the flame of your anger, a fierce energy that echoes in the heart of every story. Embrace this fire with a selection of films that channel that emotion into powerful narratives, where rage transforms into resilience and passion. Let these cinematic journeys help illuminate the path toward understanding and catharsis.",
        "color": "anger",
        "themeColor": "#ef4444",
        "movies": [
            {
                "id": 1,
                "title": "Mad Max: Fury Road",
                "genre": "Action / Sci‑Fi",
                "year": 2015,
                "rating": "8.1",
                "duration": "120 min",
                "match": "97%",
                "desc": "A woman rebels against a tyrannical ruler in post‑apocalyptic Australia.",
                "reason": "A righteous fury weaponized into devastating art.",
                "img": "/images/madmax.jpg"
            },

            {
                "id": 2,
                "title": "Network",
                "genre": "Drama / Satire",
                "year": 1976,
                "rating": "8.1",
                "duration": "121 min",
                "match": "96%",
                "desc": "A TV network exploits a deranged former anchors ravings.",
                "reason": "I am mad as hell, and I am not going to take this anymore!",
                "img": "https://image.tmdb.org/t/p/w500/pLfw8X9z3t5E55hXq7XyOItf9m2.jpg"
            },
            {
                "id": 3,
                "title": "John Wick",
                "genre": "Action / Thriller",
                "year": 2014,
                "rating": "7.4",
                "duration": "101 min",
                "match": "95%",
                "desc": "An ex-hit-man tracks down the gangsters that killed his dog.",
                "reason": "Pure, distilled vengeance fueled by unstoppable rage.",
                "img": "https://image.tmdb.org/t/p/w500/wkt91r1x1R0i63P0kZJ3wzE5zWn.jpg"
            },
            {
                "id": 4,
                "title": "Parasite",
                "genre": "Thriller / Drama",
                "year": 2019,
                "rating": "8.5",
                "duration": "132 min",
                "match": "93%",
                "desc": "The Kim family schemes to become employed by the wealthy Park family.",
                "reason": "A simmering fury about inequality and class.",
                "img": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"
            },
            {
                "id": 5,
                "title": "The Dark Knight",
                "genre": "Action / Thriller",
                "year": 2008,
                "rating": "9.0",
                "duration": "152 min",
                "match": "88%",
                "desc": "Batman fights The Joker, a chaotic criminal mastermind.",
                "reason": "Unleashed, controlled fury channeling pure dramatic power.",
                "img": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg"
            },
            {
                "id": 6,
                "title": "Fight Club",
                "genre": "Drama / Thriller",
                "year": 1999,
                "rating": "8.8",
                "duration": "139 min",
                "match": "94%",
                "desc": "An office worker forms an underground fight club.",
                "reason": "Rage against emptiness and modern life.",
                "img": "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg"
            },
            {
                "id": 7,
                "title": "Do the Right Thing",
                "genre": "Drama / Comedy",
                "year": 1989,
                "rating": "8.0",
                "duration": "120 min",
                "match": "92%",
                "desc": "Racial tension builds in a Brooklyn neighborhood on the hottest day of summer.",
                "reason": "A boiling pot of righteous, necessary anger.",
                "img": "https://image.tmdb.org/t/p/w500/yAooofX1P3e3QkUty4n4g7P1q4J.jpg"
            },
            {
                "id": 8,
                "title": "Gladiator",
                "genre": "Action / Drama",
                "year": 2000,
                "rating": "8.5",
                "duration": "155 min",
                "match": "91%",
                "desc": "A former Roman General sets out to exact vengeance.",
                "reason": "Epic, visceral vengeance and enduring fury.",
                "img": "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvq0.jpg"
            },
            {
                "id": 9,
                "title": "V for Vendetta",
                "genre": "Action / Sci-Fi",
                "year": 2005,
                "rating": "8.2",
                "duration": "132 min",
                "match": "89%",
                "desc": "A masked freedom fighter known as V fights a totalitarian government.",
                "reason": "A passionate and angry cry against fascism.",
                "img": "https://image.tmdb.org/t/p/w500/vQqyeb1NnvKibH5Nls9P07pY1R8.jpg"
            },
            {
                "id": 10,
                "title": "Kill Bill: Vol. 1",
                "genre": "Action / Thriller",
                "year": 2003,
                "rating": "8.2",
                "duration": "111 min",
                "match": "87%",
                "desc": "After awakening from a four-year coma, a former assassin wreaks vengeance.",
                "reason": "A stylish, relentless bloodbath fueled by betrayal.",
                "img": "https://image.tmdb.org/t/p/w500/v7TaX8kXzHq2mP4H7bQvKxI1bJ.jpg"
            }
        ]
    },
    "Sadness": {
        "quote": "I sense the quiet weight of your sadness, a gentle ache that deserves to be felt. Let these melancholic and profoundly moving films wrap around you, offering a space to cry, to reflect, and to find the tender beauty hidden in heartbreak.",
        "color": "sadness",
        "themeColor": "#3b82f6",
        "movies": [
            {
                "id": 1,
                "title": "Manchester by the Sea",
                "genre": "Drama",
                "year": 2016,
                "rating": "7.8",
                "duration": "137 min",
                "match": "97%",
                "desc": "An uncle cares for his teenage nephew after his brother dies.",
                "reason": "An unflinching, powerful look at grief and enduring sorrow.",
                "img": "https://image.tmdb.org/t/p/w500/p40x794rT2hCioHInB1vB2S6eXg.jpg"
            },
            {
                "id": 2,
                "title": "Schindler's List",
                "genre": "Biography / Drama",
                "year": 1993,
                "rating": "9.0",
                "duration": "195 min",
                "match": "95%",
                "desc": "Oskar Schindler becomes concerned for his Jewish workforce.",
                "reason": "A devastating masterpiece confronting humanity\u2019s darkest hours.",
                "img": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg"
            },
            {
                "id": 3,
                "title": "The Green Mile",
                "genre": "Crime / Drama",
                "year": 1999,
                "rating": "8.6",
                "duration": "189 min",
                "match": "93%",
                "desc": "Death Row guards interact with a unique inmate.",
                "reason": "A deeply emotional and tragic story of innocence.",
                "img": "https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg"
            },
            {
                "id": 4,
                "title": "Grave of the Fireflies",
                "genre": "Animation / Drama",
                "year": 1988,
                "rating": "8.5",
                "duration": "89 min",
                "match": "96%",
                "desc": "Two siblings struggle to survive in Japan during WWII.",
                "reason": "One of the most profoundly heartbreaking films ever made.",
                "img": "https://image.tmdb.org/t/p/w500/qG3RYlIVpTYclR9cKVVqCRDkOQ.jpg"
            },
            {
                "id": 5,
                "title": "Eternal Sunshine of the Spotless Mind",
                "genre": "Romance / Sci-Fi",
                "year": 2004,
                "rating": "8.3",
                "duration": "108 min",
                "match": "94%",
                "desc": "A couple undergo a procedure to erase each other from their memories.",
                "reason": "A beautiful, melancholic look at the pain of lost love.",
                "img": "https://image.tmdb.org/t/p/w500/5MwkWH9tx75G6BabmM5zB21y1P0.jpg"
            },
            {
                "id": 6,
                "title": "The Father",
                "genre": "Drama",
                "year": 2020,
                "rating": "8.2",
                "duration": "97 min",
                "match": "92%",
                "desc": "A man refuses assistance from his daughter as he ages.",
                "reason": "A devastating portrayal of memory loss and aging.",
                "img": "https://image.tmdb.org/t/p/w500/1Xdd32t2f180q9mI5eInbY4aL1R.jpg"
            },
            {
                "id": 7,
                "title": "A Ghost Story",
                "genre": "Drama / Fantasy",
                "year": 2017,
                "rating": "6.8",
                "duration": "92 min",
                "match": "91%",
                "desc": "A deceased husband remains to watch over his grieving wife.",
                "reason": "A quiet, existential exploration of time and lingering sadness.",
                "img": "https://image.tmdb.org/t/p/w500/tLia0RarX17n0aYV9pYt0Yc8yP3.jpg"
            },
            {
                "id": 8,
                "title": "Brokeback Mountain",
                "genre": "Drama / Romance",
                "year": 2005,
                "rating": "7.5",
                "duration": "134 min",
                "match": "90%",
                "desc": "A secret and tragic romance between two cowboys.",
                "reason": "A deeply aching tale of forbidden love and regret.",
                "img": "https://image.tmdb.org/t/p/w500/vQikEw2S82RXXa71gW2rR3T05O.jpg"
            },
            {
                "id": 9,
                "title": "The Elephant Man",
                "genre": "Biography / Drama",
                "year": 1980,
                "rating": "8.2",
                "duration": "124 min",
                "match": "88%",
                "desc": "A deformed man is rescued from a freak show.",
                "reason": "A tragic and incredibly moving testament to human dignity.",
                "img": "https://image.tmdb.org/t/p/w500/eP49P5e2xTj82Xb1x1P2xT2V.jpg"
            },
            {
                "id": 10,
                "title": "Melancholia",
                "genre": "Drama / Sci-Fi",
                "year": 2011,
                "rating": "7.1",
                "duration": "130 min",
                "match": "87%",
                "desc": "Two sisters relations are strained as a rogue planet approaches Earth.",
                "reason": "A stunning visual metaphor for deep clinical depression.",
                "img": "https://image.tmdb.org/t/p/w500/xZ1P1Q62J9wJ3R8m0QW3m8gA.jpg"
            }
        ]
    },
    "Fear": {
        "quote": "I feel the chilling grip of your fear, that sharp instinct keeping you alert in the dark. Embrace the thrill with these terrifying, edge-of-your-seat masterpieces that will make your heart race and test your nerves. Don't look behind you.",
        "color": "fear",
        "themeColor": "#a855f7",
        "movies": [
            {
                "id": 1,
                "title": "The Shining",
                "genre": "Horror / Mystery",
                "year": 1980,
                "rating": "8.4",
                "duration": "146 min",
                "match": "98%",
                "desc": "A family heads to an isolated hotel for the winter.",
                "reason": "A masterclass in dread and psychological terror.",
                "img": "https://image.tmdb.org/t/p/w500/x2OJBkZqf11bYFhWpINfQpA5hM9.jpg"
            },
            {
                "id": 2,
                "title": "Alien",
                "genre": "Horror / Sci-Fi",
                "year": 1979,
                "rating": "8.5",
                "duration": "117 min",
                "match": "96%",
                "desc": "A commercial spacecraft encounter a deadly lifeform.",
                "reason": "Claustrophobic, relentless, and truly terrifying.",
                "img": "https://image.tmdb.org/t/p/w500/vfrQk5PIZpkE04xQjPIyy1Z6i00.jpg"
            },
            {
                "id": 3,
                "title": "Hereditary",
                "genre": "Horror / Drama",
                "year": 2018,
                "rating": "7.3",
                "duration": "127 min",
                "match": "94%",
                "desc": "A grieving family is haunted by tragic occurrences.",
                "reason": "A deeply unsettling modern horror classic.",
                "img": "https://image.tmdb.org/t/p/w500/4gC2A1P32sR4j08qYf3r2P0396X.jpg"
            },
            {
                "id": 4,
                "title": "The Thing",
                "genre": "Horror / Sci-Fi",
                "year": 1982,
                "rating": "8.2",
                "duration": "109 min",
                "match": "95%",
                "desc": "Researchers in Antarctica are hunted by a shape-shifting alien.",
                "reason": "Paranoia and isolation distilled into pure fear.",
                "img": "https://image.tmdb.org/t/p/w500/tzgjTvgJZItcs7L2qHlqT8YfPq.jpg"
            },
            {
                "id": 5,
                "title": "Get Out",
                "genre": "Horror / Thriller",
                "year": 2017,
                "rating": "7.8",
                "duration": "104 min",
                "match": "93%",
                "desc": "A young African-American visits his white girlfriend's parents.",
                "reason": "A brilliant, tension-filled masterpiece of social horror.",
                "img": "https://image.tmdb.org/t/p/w500/tX6WnWJb1g6o1Z1D3U7t9UaXmX.jpg"
            },
            {
                "id": 6,
                "title": "Psycho",
                "genre": "Horror / Mystery",
                "year": 1960,
                "rating": "8.5",
                "duration": "109 min",
                "match": "92%",
                "desc": "A secretary ends up at a secluded motel.",
                "reason": "The film that invented the modern slasher.",
                "img": "https://image.tmdb.org/t/p/w500/cWcOExqTjXq1yT3U8zT6T1Q4U3V.jpg"
            },
            {
                "id": 7,
                "title": "The Exorcist",
                "genre": "Horror",
                "year": 1973,
                "rating": "8.1",
                "duration": "122 min",
                "match": "91%",
                "desc": "A teenage girl is possessed by a mysterious entity.",
                "reason": "A visceral, shocking battle between good and evil.",
                "img": "https://image.tmdb.org/t/p/w500/4nQpdD3Cj7bH0zG8tD5p4U3M8vO.jpg"
            },
            {
                "id": 8,
                "title": "A Quiet Place",
                "genre": "Horror / Sci-Fi",
                "year": 2018,
                "rating": "7.5",
                "duration": "90 min",
                "match": "90%",
                "desc": "A family must live in silence to hide from monsters.",
                "reason": "A nerve-wracking exercise in tension and silence.",
                "img": "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5jcSQeRM51H5VlP.jpg"
            },
            {
                "id": 9,
                "title": "The Babadook",
                "genre": "Horror / Drama",
                "year": 2014,
                "rating": "6.8",
                "duration": "93 min",
                "match": "89%",
                "desc": "A single mother battles her son's fear of a monster.",
                "reason": "A creeping, psychological terror born from grief.",
                "img": "https://image.tmdb.org/t/p/w500/e9C1X1XhX81X9cE2h2E8V5K3V3h.jpg"
            },
            {
                "id": 10,
                "title": "Rosemary's Baby",
                "genre": "Horror / Drama",
                "year": 1968,
                "rating": "8.0",
                "duration": "137 min",
                "match": "88%",
                "desc": "A pregnant woman suspects her neighbors are part of a cult.",
                "reason": "A slow-burn descent into paranoia and terror.",
                "img": "https://image.tmdb.org/t/p/w500/a2uE2rGz2N0Z3Q8E9U7b8U9Yp0X.jpg"
            }
        ]
    },
    "Disgust": {
        "quote": "I sense your disgust, a visceral reaction to the grim, the grotesque, and the uncomfortably real. Challenge your senses with these daring, provocative, and unsettling films that push boundaries and dive deep into the uncomfortable.",
        "color": "disgust",
        "themeColor": "#22c55e",
        "movies": [
            {
                "id": 1,
                "title": "Se7en",
                "genre": "Crime / Drama",
                "year": 1995,
                "rating": "8.6",
                "duration": "127 min",
                "match": "96%",
                "desc": "Detectives hunt a serial killer using the seven deadly sins.",
                "reason": "A grim, gritty, and deeply disturbing dive into muck.",
                "img": "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg"
            },
            {
                "id": 2,
                "title": "The Fly",
                "genre": "Drama / Horror",
                "year": 1986,
                "rating": "7.6",
                "duration": "96 min",
                "match": "94%",
                "desc": "A scientist begins to transform into a giant fly.",
                "reason": "Incredible body horror that is tragic and repulsive.",
                "img": "https://image.tmdb.org/t/p/w500/w0qAEnb227n3hWpG4f6q0p9o2yY.jpg"
            },
            {
                "id": 3,
                "title": "Requiem for a Dream",
                "genre": "Drama",
                "year": 2000,
                "rating": "8.3",
                "duration": "102 min",
                "match": "92%",
                "desc": "Drug-induced utopias are shattered by addiction.",
                "reason": "A grueling, visceral descent into despair.",
                "img": "https://image.tmdb.org/t/p/w500/nOd6vjEmzCT0k4VYqsA2hwyi87C.jpg"
            },
            {
                "id": 4,
                "title": "The Silence of the Lambs",
                "genre": "Crime / Thriller",
                "year": 1991,
                "rating": "8.6",
                "duration": "118 min",
                "match": "95%",
                "desc": "An FBI cadet seeks the help of a cannibal killer.",
                "reason": "A chilling and gruesome psychological thriller.",
                "img": "https://image.tmdb.org/t/p/w500/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg"
            },
            {
                "id": 5,
                "title": "Midsommar",
                "genre": "Horror / Drama",
                "year": 2019,
                "rating": "7.1",
                "duration": "148 min",
                "match": "93%",
                "desc": "A couple travels to a Swedish festival that devolves into a cult.",
                "reason": "Bright, sunny, and incredibly sickening.",
                "img": "https://image.tmdb.org/t/p/w500/m110vLa9sWfR3W7Z2Z2GzU5wZ9M.jpg"
            },
            {
                "id": 6,
                "title": "Eraserhead",
                "genre": "Horror / Fantasy",
                "year": 1977,
                "rating": "7.3",
                "duration": "89 min",
                "match": "91%",
                "desc": "A man tries to survive his angry girlfriend and mutant child.",
                "reason": "A surreal nightmare of grotesque imagery.",
                "img": "https://image.tmdb.org/t/p/w500/wA2R8Y7MhBqg8Pwq6rPqgA8rD0T.jpg"
            },
            {
                "id": 7,
                "title": "Oldboy",
                "genre": "Action / Mystery",
                "year": 2003,
                "rating": "8.4",
                "duration": "120 min",
                "match": "90%",
                "desc": "A man imprisoned for 15 years seeks revenge.",
                "reason": "Brutal, shocking, and morally sickening.",
                "img": "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQy70VvA.jpg"
            },
            {
                "id": 8,
                "title": "District 9",
                "genre": "Action / Sci-Fi",
                "year": 2009,
                "rating": "7.9",
                "duration": "112 min",
                "match": "89%",
                "desc": "An alien refugee camp in South Africa deteriorates.",
                "reason": "Visceral body horror meets societal disgust.",
                "img": "https://image.tmdb.org/t/p/w500/c0Nsw0lOaM3bHwK9Z2pUuM4B9T.jpg"
            },
            {
                "id": 9,
                "title": "American Psycho",
                "genre": "Crime / Drama",
                "year": 2000,
                "rating": "7.6",
                "duration": "102 min",
                "match": "88%",
                "desc": "A wealthy investment banker hides his psychopathic ego.",
                "reason": "A repulsive, bloody look at soulless materialism.",
                "img": "https://image.tmdb.org/t/p/w500/wS5v41sR9Kz1rGfQjXvH9PzL2L.jpg"
            },
            {
                "id": 10,
                "title": "The Human Centipede",
                "genre": "Horror",
                "year": 2009,
                "rating": "4.4",
                "duration": "92 min",
                "match": "87%",
                "desc": "A mad scientist kidnaps tourists for a sick experiment.",
                "reason": "The absolute definition of cinematic revulsion.",
                "img": "https://image.tmdb.org/t/p/w500/qM2y2gE3hM9rT6A4E2g1J2G4D7R.jpg"
            }
        ]
    },
    "Anxiety": {
        "quote": "I can feel the nervous hum of your anxiety, the tension pulling tight in your chest. Let that energy flow into these suspenseful, nail-biting thrillers that perfectly capture the feeling of running out of time and gripping the edge of your seat.",
        "color": "anxiety",
        "themeColor": "#f97316",
        "movies": [
            {
                "id": 1,
                "title": "Uncut Gems",
                "genre": "Crime / Thriller",
                "year": 2019,
                "rating": "7.4",
                "duration": "135 min",
                "match": "99%",
                "desc": "A New York jeweler risks everything to pay his debts.",
                "reason": "A non-stop panic attack captured on film.",
                "img": "https://image.tmdb.org/t/p/w500/6XN1vxHc7kUSqNWtR94nS7o9x3B.jpg"
            },
            {
                "id": 2,
                "title": "Whiplash",
                "genre": "Drama / Music",
                "year": 2014,
                "rating": "8.5",
                "duration": "106 min",
                "match": "95%",
                "desc": "A promising young drummer is pushed to his limits.",
                "reason": "Intense, demanding, and utterly nerve-wracking.",
                "img": "/images/whiplash.jpg"
            },
            {
                "id": 3,
                "title": "Good Time",
                "genre": "Crime / Thriller",
                "year": 2017,
                "rating": "7.3",
                "duration": "101 min",
                "match": "93%",
                "desc": "A bank robber tries to free his brother from prison.",
                "reason": "A chaotic, desperate race against the clock.",
                "img": "https://image.tmdb.org/t/p/w500/nN5k168XwD6Tz5pXy1rP0iQGv3R.jpg"
            },
            {
                "id": 4,
                "title": "Sorcerer",
                "genre": "Adventure / Thriller",
                "year": 1977,
                "rating": "7.7",
                "duration": "121 min",
                "match": "94%",
                "desc": "Four outcasts must drive trucks filled with unstable dynamite.",
                "reason": "White-knuckle tension that will stop your heart.",
                "img": "https://image.tmdb.org/t/p/w500/9bQ5P1Y8y5V8W1T7tM2rJ2m1zG.jpg"
            },
            {
                "id": 5,
                "title": "Gravity",
                "genre": "Sci-Fi / Thriller",
                "year": 2013,
                "rating": "7.7",
                "duration": "91 min",
                "match": "92%",
                "desc": "Two astronauts work together to survive after an accident.",
                "reason": "A breathtaking, stress-inducing fight for survival.",
                "img": "https://image.tmdb.org/t/p/w500/uB2nIfB1y5hVb0F1YqT6T1Q4U3V.jpg"
            },
            {
                "id": 6,
                "title": "Shiva Baby",
                "genre": "Comedy / Drama",
                "year": 2020,
                "rating": "7.2",
                "duration": "77 min",
                "match": "91%",
                "desc": "A young woman runs into her sugar daddy at a shiva.",
                "reason": "Claustrophobic, painfully awkward social anxiety.",
                "img": "https://image.tmdb.org/t/p/w500/1pP9u1U3pDqM8R2hVj5D4X3R4dK.jpg"
            },
            {
                "id": 7,
                "title": "Prisoners",
                "genre": "Crime / Thriller",
                "year": 2013,
                "rating": "8.1",
                "duration": "153 min",
                "match": "90%",
                "desc": "A father takes matters into his own hands when his daughter goes missing.",
                "reason": "A grim, pulse-pounding thriller about desperation.",
                "img": "https://image.tmdb.org/t/p/w500/u1T5P1Q5Z7R8D4X3R4dK1pP9u.jpg"
            },
            {
                "id": 8,
                "title": "Sicario",
                "genre": "Action / Crime",
                "year": 2015,
                "rating": "7.6",
                "duration": "121 min",
                "match": "89%",
                "desc": "An FBI agent is enlisted to aid in the drug war.",
                "reason": "A tense, brooding descent into a violent world.",
                "img": "https://image.tmdb.org/t/p/w500/wM2U1U3pDqM8R2hVj5D4X3R4dK.jpg"
            },
            {
                "id": 9,
                "title": "No Country for Old Men",
                "genre": "Crime / Thriller",
                "year": 2007,
                "rating": "8.1",
                "duration": "122 min",
                "match": "88%",
                "desc": "Violence and mayhem ensue after a hunter stumbles upon a drug deal.",
                "reason": "A relentlessly tense game of cat and mouse.",
                "img": "https://image.tmdb.org/t/p/w500/uB2nIfB1y5hVb0F1YqT6T1Q4U3V.jpg"
            },
            {
                "id": 10,
                "title": "Boiling Point",
                "genre": "Drama / Thriller",
                "year": 2021,
                "rating": "7.5",
                "duration": "92 min",
                "match": "87%",
                "desc": "A head chef wrangles his team on the busiest day of the year.",
                "reason": "A stressful, continuous-shot nightmare in a kitchen.",
                "img": "https://image.tmdb.org/t/p/w500/wM2U1U3pDqM8R2hVj5D4X3R4dK.jpg"
            }
        ]
    }
};
